# **Energy consumption Prediction Using - XGboos Time series analysis**

### Importing Important Dependencies

In [3]:
# Essential Libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

# Model Importing

## Data collection

In [4]:
df = pd.read_csv(r'D:\Robotics\Machine Learning Projects\XGboost Based Energy Consumption prediction\data\PJME_hourly.csv')

In [5]:
df.head()

              Datetime  PJME_MW
0  2002-12-31 01:00:00  26498.0
1  2002-12-31 02:00:00  25147.0
2  2002-12-31 03:00:00  24574.0
3  2002-12-31 04:00:00  24393.0
4  2002-12-31 05:00:00  24860.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145366 entries, 0 to 145365
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   Datetime  145366 non-null  object
 1   PJME_MW   145366 non-null  float64
dtypes: float64(1), object(1)
memory usage: 2.2+ MB

In [8]:
df.describe()

             PJME_MW
count  145366.000000
mean    32080.222831
std      6464.012166
min     14544.000000
25%     27573.000000
50%     31421.000000
75%     35650.000000
max     62009.000000

In [9]:
df.isnull().sum()

Datetime    0
PJME_MW     0
dtype: int64

From Above we can see there is no missing values in this dataset so the cleaning process is reduced