# Movie Recommendation system 


## Project Overview



**Objective of the Project** 

- Create clean data cleaning and proccessing pipeline for movie data
- Implement cosine similarity for movie recommendations
- Deploy the project to make it end-to-end project

## Importing dependencies

In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

### Getting the data to the notebook

In [2]:

df_v1 = pd.read_csv(r"D:\Robotics\Machine Learning Projects\Movie Recommendation System\data\movies_metadata - Copy.csv")

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_19132\2270473104.py:1: DtypeWarning: Columns (0: popularity) have mixed types. Specify dtype option on import or set low_memory=False.
  df_v1 = pd.read_csv(r"D:\Robotics\Machine Learning Projects\Movie Recommendation System\data\movies_metadata - Copy.csv")

In [3]:
df_v1.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

## Exploratory data analysis and base data cleaning

In [4]:
print(f"shape of the data set is {df_v1.shape} ")

shape of the data set is (45466, 24)

In [5]:
df_v1.info()

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  str
 1   belongs_to_collection  4494 non-null   str
 2   budget                 45466 non-null  str
 3   genres                 45466 non-null  str
 4   homepage               7782 non-null   str
 5   id                     45466 non-null  str
 6   imdb_id                45449 non-null  str
 7   original_language      45455 non-null  str
 8   original_title         45466 non-null  str
 9   overview               44512 non-null  str
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  str
 12  production_companies   45463 non-null  str
 13  production_countries   45463 non-null  str
 14  release_date           45379 non-null  str
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  str
 18  status                 45379 non-null  str
 19  tagline                20412 non-null  str
 20  title                  45460 non-null  str
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(2), str(18)
memory usage: 8.3+ MB

In [6]:
df_v1.describe()

            revenue       runtime  vote_average    vote_count
count  4.546000e+04  45203.000000  45460.000000  45460.000000
mean   1.120935e+07     94.128199      5.618207    109.897338
std    6.433225e+07     38.407810      1.924216    491.310374
min    0.000000e+00      0.000000      0.000000      0.000000
25%    0.000000e+00     85.000000      5.000000      3.000000
50%    0.000000e+00     95.000000      6.000000     10.000000
75%    0.000000e+00    107.000000      6.800000     34.000000
max    2.787965e+09   1256.000000     10.000000  14075.000000

In [7]:
df_v1.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [8]:
df_v1.duplicated().sum()

np.int64(13)

In [9]:
df_v1 = df_v1.drop_duplicates()

In [10]:
df_v1.duplicated().sum()

np.int64(0)

In [11]:
df_v1.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='str')

**Insights**
- Data set is majorly consisting str data type
- integer type dataset are column (revenue , vote_count , vote_average , runtime)
- We have to total of ['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'] columns but for the model we will not be needing this much feature , so we will be selecting the best features for the model

## Feature selection 
## 🥇 Essential (Must-Have Features)
These 6 columns carry 80–90% of the predictive signal for your recommender.

1. **genres**

Why: The single strongest categorical signal. User preferences heavily anchor on genre (e.g., Action vs. Romance).

2. **overview**

Why: Plot summaries contain rich textual information (themes, tropes, settings) ideal for NLP similarity modeling.

3. **title**

Why: Required as the human-readable output label for your recommendations.

4. **id (or imdb_id)**

Why: Essential system primary key for indexing, deduplication, and joining with other datasets.

5. **vote_count**

Why: Crucial quality control. Filters out obscure films with 1 artificial "10/10" rating before calculating scores.

6. **vote_average**

Why: Core metric for quality weighting (e.g., combining with vote_count using IMDb’s weighted rating formula).

In [13]:
missing = df_v1.isnull().sum()
missing[missing>0]

belongs_to_collection    40959
homepage                 37673
imdb_id                     17
original_language           11
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25045
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [14]:
df_v1 = df_v1[['title','overview','genres','tagline','vote_average','popularity']]

In [15]:
df_v1.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [16]:
df_v1.isnull().sum()

title               6
overview          954
genres              0
tagline         25045
vote_average        6
popularity          5
dtype: int64

### Handling missing values

In [ ]:
# For title it only have 6 missing values so we can directly remove those from the data
df_v1 = df_v1.dropna(subset=['title'])

Handling overview column by filling them with empty string

In [18]:
df_v1['overview'] =df_v1['overview'].fillna('')

**Handling genres column**

In [19]:
df_v1.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [21]:
import ast
df_v1['genres']= df_v1['genres'].apply(lambda x:" ".join(i['name'] for i in ast.literal_eval(x)))

In [22]:
df_v1['genres'].head()

0     Animation Comedy Family
1    Adventure Fantasy Family
2              Romance Comedy
3        Comedy Drama Romance
4                      Comedy
Name: genres, dtype: str

In [24]:
df_v1.isnull().sum()

title               0
overview            0
genres              0
tagline         25039
vote_average        0
popularity          0
dtype: int64

In [23]:
df_v1.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

**Handling tagline column**

In [25]:
df_v1['tagline'] = df_v1['tagline'].fillna('')

In [27]:
df_v1.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

### missing value handling insights 

- Major handling strategy we used is replacing missing values with empty string 
- genre column was little interesting to handle as it contains id and name but we only want name of the genre so we use `ast` to handle it in conjuction with lamba function

### Feature engineering 
Creating new usefull feature using current features 

we are makings `tags` column using columns such as `overview` , `genres` , `tagline`

In [28]:
df_v1['tags']= df_v1['overview']+" "+df_v1['genres']+" "+df_v1['tagline']

In [29]:
df_v1.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [30]:
df_v1['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

## Text data processing

In [53]:
import nltk 
from  nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [54]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [55]:
stopwords = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [56]:
def preprocess_text(text):
    # Handle edge cases
    if pd.isna(text) or not isinstance(text, str):
        return ""
    
    # Lowercase
    text = text.lower()
    
    # Remove punctuation but KEEP SPACES (IMPORTANT!)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)  # ← Added \s
    
    # Split into words
    words = text.split()
    
    # Remove stopwords
    words = [word for word in words if word not in stopwords]
    
    # Lemmatize
    words = [lemmatizer.lemmatize(word) for word in words]
    
    # Join back
    return " ".join(words)

### Testing the preprocess function

In [37]:
print(preprocess_text("I'm loving this movie!!!"))

imlovingthismovie

In [38]:
print(preprocess_text("State-of-the-art technology"))

stateofthearttechnology

In [39]:
test_text = """
I'm absolutely LOVING this movie!!! It's the best film I've seen in 2024. 
The acting was phenomenal - truly state-of-the-art performance by the cast. 
Don't you think so? Well, I watched it 3 times already!! 
The director's vision is simply breathtaking... 
P.S. - Can't wait for the sequel! #MovieMagic
"""

In [58]:
test_text1 = """"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"
"""

In [57]:
print(preprocess_text(test_text))

im absolutely loving movie best film ive seen 2024 acting phenomenal truly stateoftheart performance cast dont think well watched 3 time already director vision simply breathtaking p cant wait sequel moviemagic

In [59]:
print(preprocess_text(test_text1))

sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game 26 year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement

In [60]:
df_v1['tags']= df_v1['tags'].apply(preprocess_text)

In [61]:
df_v1 = df_v1.reset_index(drop=True)

In [63]:
indices = pd.Series(df_v1.index,index= df_v1['title']).drop_duplicates()

In [64]:
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [ ]:
# df_v1.to_csv(
#     r"D:\Robotics\Machine Learning Projects\Movie Recommendation System\data\movies_processed.csv",
#     index=False
# )

## Text vectorization 

Converting text dato into numerical vectors 

`TfidfVectorizer` is a tool from scikit-learn that converts text data into numerical features that machine learning algorithms can understand. It transforms a collection of text documents into a matrix of TF-IDF features.

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [66]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [67]:
tfidf_matrix = tfidf.fit_transform(df_v1['tags'])

In [68]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1555864 stored elements and shape (45447, 50000)>

## Applying cosine similarity

In [69]:
from sklearn.metrics.pairwise import cosine_similarity

In [71]:
def recommend(title,n=10):
    if title not in indices:
        return ['Movie not found']

    idx = indices[title]
    sim_score = cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
    similar_idx = sim_score.argsort()[::-1][1:n+1]
    return df_v1['title'].iloc[similar_idx]

In [72]:
recommend('Avatar',5)

26547                  Avatar 2
13883      The Inhabited Island
26553            Thor: Ragnarok
28633      Stand by Me Doraemon
43431    Moontrap: Target Earth
Name: title, dtype: str

In [73]:
import pickle
pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))
df_v1.to_pickle('df_v1.pkl')
pickle.dump(tfidf,open('tfidf.pkl','wb'))